### ISSUE TITLE
HTML Entities

### ISSUE THREAD

**Issue by sdhunt** [paulmougin/prj-rev-bwfs-dasmoto#4]
https://github.com/paulmougin/prj-rev-bwfs-dasmoto/blob/ae14e83b61fa684f1841162b3bf73fcb8aeaf9e2/DasmotosArtsCrafts/index.html#L10

Although modern browsers will render a lone ampersand (`&`) verbatim, it is better to treat the ampersand as the "special character" that it is, and declare the full HTML entity code: `&amp;`.

See 
* https://stackoverflow.com/questions/3493405/do-i-really-need-to-encode-as-amp
* https://developer.mozilla.org/en-US/docs/Glossary/Entity

**Comment by paulmougin** [comment]
Got it. I have also checked an extra link from the one your shared with me: https://dev.w3.org/html5/html-author/charref
