### ISSUE TITLE
CSS could be simplified a little

### ISSUE THREAD

**Issue by sdhunt** [paulmougin/prj-rev-bwfs-dasmoto#5]
https://github.com/paulmougin/prj-rev-bwfs-dasmoto/blob/ae14e83b61fa684f1841162b3bf73fcb8aeaf9e2/DasmotosArtsCrafts/ressources/style.css#L1-L4

Your CSS gets the job done, and this is fine. A good habit to get into is to strive for conciseness; with that in mind, remember that the "global" selector can be used to apply styles to _every_ element in the document:

    * {
      font-family: Helvetica;
    }

Also, try to remember to follow the conventional layout for CSS code:
* include a space before the opening `{` of a rule
* no additional blank lines within the rule body `{ ... }`

**Comment by paulmougin** [comment]
Thanks for the tip 👍 The Magic Star selector is really helpful.
