### ISSUE TITLE
SUMMARY: Meets Expectations

### ISSUE THREAD

**Issue by sdhunt** [paulmougin/prj-rev-bwfs-dasmoto#6]
_Grade:_ __Meets Expectations__

This is a great first step into writing awesome web pages!

You should feel good about:
* Meeting the client specification
* Nicely structured HTML
* Remembering to use `alt` attributes in `<img>` tags
* Correct use of `id` and `class` attributes

There are a few things to pay attention to, to make your code even better:
* Remember the global selector (`*`)
* Insert a space between a CSS rule selector and the opening brace `{` of the rule body
* Don't insert additional blanklines inside CSS rule body
* Remember to use the full HTML entity code for rendering ampersand: `&amp;`

Keep up the good work!

**Comment by paulmougin** [comment]
👍 Thank you
